sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - curl https://install.meteor.com | /bin/sh
install:
  - git clean -fXd
  - npm cache verify
  - npm install -g concurrently
script:
  - ./run_tests.sh
