language: node_js
node_js:
    - "0.10"
before_install:
  - curl https://install.meteor.com | /bin/sh
script:
  - VELOCITY_TEST_PACKAGES=1 meteor test-packages --driver-package velocity:html-reporter --velocity ./

